name: uju_app
description: "uju.mn"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_signin_button: ^2.0.0
  ant_design_flutter: ^0.0.1+5
  http: ^0.13.3
  fluttertoast: ^8.0.8
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  analyzer: ^6.4.1
  get: ^4.6.6
  provider: ^6.1.2
  badges: ^3.1.2
  flutter_secure_storage: ^4.2.1
  jwt_decode: ^0.3.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/uju4.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: NotoSans
      fonts:
        - asset: lib/assets/fonts/NotoSans-Regular.ttf
        - asset: lib/assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/NotoSans-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/NotoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/NotoSans_Condensed-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/NotoSans_Condensed-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/NotoSans_Condensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/NotoSans_Condensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/NotoSans_Condensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/NotoSans_Condensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Regular.ttf
        - asset: lib/assets/fonts/NotoSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/NotoSans_Condensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/NotoSans_Condensed-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/NotoSans_Condensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Regular.ttf
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/NotoSans_ExtraCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Regular.ttf
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/NotoSans_SemiCondensed-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/assets/fonts/NotoSans-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/NotoSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: lib/assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/assets/fonts/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/NotoSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: lib/assets/fonts/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/NotoSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: lib/assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/NotoSans-Regular.ttf
        - asset: lib/assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/NotoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/assets/fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
